#version: "3.8"
services:
  backend:
    build: ./backend
    image: solucity-backend:latest
    ports:
      - "8080:8080"


  frontend:
    build: ./frontend
    image: solucity-frontend:latest
    ports:
      - "80:80"
