#version: "3.8"
services:
  backend:
    build: ./backend
    image: solucity-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.31.249.167:5432/solucity-bdd_int
      SPRING_DATASOURCE_USERNAME: SolucityBDD_int
      SPRING_DATASOURCE_PASSWORD: solucity


  frontend:
    build: ./frontend
    image: solucity-frontend:latest
    ports:
      - "80:80"
